### PR TITLE
feat: adding logs and timeout and ssl policy parameters to external load balancer

### PR DESCRIPTION
**Pull request by rs1986x**
What's changed, or what was fixed?

- added log configuration for the mig-l7xlb module
- added timeout configuration for mig-l7xlb
- added ssl policy configuration for mig-l7xlb

**Fixes:* #issue

- [x] I have run all the tests locally and they all pass.
- [x] I have followed the relevant style guide for my changes.

### CODE REVIEW

**Comment by rs1986x** [comment]
the linting errors are not from my code change, those were already in main [see here](https://github.com/apigee/terraform-modules/actions/runs/4197025043/jobs/7278805739#step:6:2375)

**Comment by riccardosalamanna** [comment]
there was a megalint error on another module that i didn't modify, nonetheless i deleted those variables that were not in use, can somebody validate the pr thanks :)

**Comment by g-greatdevaks** [comment]
Thanks for the PR, @rs1986x.
I am having the open PRs reviewed and will have the new release made as soon as possible.

**Review by g-greatdevaks — APPROVED** [review]
LGTM.
Ideally, now onwards, optional variables should be introduced with the Terraform optional variables.

**Pull request merged**
