### PR TITLE
Feat: added edge_security_policy to nb-psc-l7xlb

### PR DESCRIPTION
**Pull request by reiniervanderhoeven**
What's changed, or what was fixed?

- item 1
- item 2

**Fixes:** #issue

- [x] I have run all the tests locally and they all pass.
- [x] I have followed the relevant style guide for my changes.

### CODE REVIEW

**Comment by danistrebel** [comment]
Thanks for the PR @reiniervanderhoeven , No problems from my end. 

On the two failed actions:

- Can you please use the automated code generation instead of the manual edit?  Just running `./tools/update-docs.sh` should do the trick.
- You can ignore the commit linter. The linter is checking if the commit is a valid [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) so we can use it to generate release notes. No worries.

**Review by danistrebel — APPROVED** [review]

**Comment by danistrebel** [comment]
@reiniervanderhoeven the cla bot failed because one of the user accounts that were used in the commits didn't accept the CLA. Can you either accept the CLA for both users or change the author for the last two commits?

**Comment by reiniervanderhoeven** [comment]
> @reiniervanderhoeven the cla bot failed because one of the user accounts that were used in the commits didn't accept the CLA. Can you either accept the CLA for both users or change the author for the last two commits?

I've added the CLA for the other account as well.

**Comment by danistrebel** [comment]
Thanks @reiniervanderhoeven  🚀

**Pull request merged**
